name: example
description: "DOO CX Flutter SDK example application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  doo_cx_flutter_sdk_plus:
    path: ../
  cupertino_icons: ^1.0.8
  image: ^4.2.0
  path_provider: ^2.1.4
  image_picker: ^1.1.2
  flutter_riverpod: ^2.5.3
  webview_flutter_web: ^0.2.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/doo_logo.png
    - assets/logo_grey.jpg
